#!/bin/sh
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -eu

VERSION=16.0.04
HERE="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$HERE/main/fonts/epaper_154g_caption_font.h"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' 0
trap 'exit 1' HUP INT TERM

SHA256=f9c8c7802453f47be02677176aeac2342ee96d354fad7a26cedcce48e68e1d9f
curl -fsSL -o "$TMP/unifont.hex.gz" \
    "https://unifoundry.com/pub/unifont/unifont-$VERSION/font-builds/unifont-$VERSION.hex.gz"
echo "$SHA256  $TMP/unifont.hex.gz" | shasum -a 256 -c - >/dev/null
gzip -dc "$TMP/unifont.hex.gz" > "$TMP/unifont.hex"
cat > "$TMP/font.h" <<'HEADER'
/* GNU Unifont 16.0.04 bitmap subset, by Roman Czyborra, Paul Hardy and contributors.
 * SIL Open Font License 1.1 OR GPL-2.0-or-later WITH font embedding exception.
 * See README.md. Generated by tools/gen_epaper_154g_caption_font.sh.
 * Glyph bitmaps are unaltered 8x16 subsets; do not edit this file by hand.
 */
#pragma once
#include <stddef.h>
#include <stdint.h>
static const uint16_t epaper_154g_caption_codepoints[] = {
HEADER
LC_ALL=C awk -F: '
function hex(s,    i,n) {
    n = 0
    for (i = 1; i <= length(s); i++)
        n = n * 16 + index("0123456789ABCDEF", substr(s, i, 1)) - 1
    return n
}
length($2) == 32 {
    code = hex($1)
    # Latin, IPA, Greek, Cyrillic, Armenian, Georgian, Latin and Greek
    # extended, punctuation, currency, letterlike, arrows and math: the
    # alphabets written left to right without shaping. awk has no hex.
    if ((code >= 32 && code <= 126) || (code >= 160 && code <= 767) ||
        (code >= 880 && code <= 1327) || (code >= 1329 && code <= 1423) ||
        (code >= 4256 && code <= 4351) || (code >= 7680 && code <= 8191) ||
        (code >= 8208 && code <= 8231) || (code >= 8240 && code <= 8286) ||
        (code >= 8352 && code <= 8384) || (code >= 8448 && code <= 8527) ||
        (code >= 8592 && code <= 8959)) {
        codes[++count] = code
        bits[count] = $2
    }
}
END {
    if (count != 2308) exit 1
    for (i = 1; i <= count; i++) {
        if (i % 12 == 1) printf "    "
        printf "0x%04x,", codes[i]
        if (i % 12 == 0 || i == count) printf "\n"; else printf " "
    }
    print "};"
    print "static const uint8_t epaper_154g_caption_glyphs[][16] = {"
    for (i = 1; i <= count; i++) {
        printf "    {"
        for (j = 1; j <= 16; j++) {
            printf "0x%s", tolower(substr(bits[i], j * 2 - 1, 2))
            if (j < 16) printf ", "
        }
        printf "}, // U+%04X\n", codes[i]
    }
    print "};"
}' "$TMP/unifont.hex" >> "$TMP/font.h"
cat >> "$TMP/font.h" <<'HEADER'
static inline const uint8_t *epaper_154g_caption_glyph(uint32_t code) {
    size_t lo = 0, hi = sizeof(epaper_154g_caption_codepoints) / sizeof(epaper_154g_caption_codepoints[0]);
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        if (epaper_154g_caption_codepoints[mid] < code) lo = mid + 1; else hi = mid;
    }
    return lo < sizeof(epaper_154g_caption_codepoints) / sizeof(epaper_154g_caption_codepoints[0])
           && epaper_154g_caption_codepoints[lo] == code ? epaper_154g_caption_glyphs[lo] : NULL;
}
HEADER
cp "$TMP/font.h" "$OUT"
echo "wrote $OUT"
