# Copyright (c) Meta Platforms, Inc. and affiliates.
# Licensed under the Apache License, Version 2.0 (see LICENSE).
# Optional reply-streaming runtime from the macOS companion SDK checkout.
services:
  ma35d1-a1:
    image: muse-ma35-board-sim-ai:local
  ma35d1-s1:
    image: muse-ma35-board-sim-ai:local
  ma35h0-a1:
    image: muse-ma35-board-sim-ai:local
  ma35h0-a2:
    image: muse-ma35-board-sim-ai:local
