#!/usr/bin/env python3
"""Generate public HealthKit identifiers/value labels from the selected watchOS SDK."""
import json, os, re, subprocess
from pathlib import Path
sdk = Path(subprocess.check_output(['xcrun', '--sdk', 'watchos', '--show-sdk-path'], text=True).strip())
headers = sdk / 'System/Library/Frameworks/HealthKit.framework/Headers'
labels = lambda s: re.sub(r'(?<=[a-z0-9])(?=[A-Z])', ' ', s)
enums = {}
for name, body in re.findall(r'typedef NS_ENUM\(NSInteger, (HKCategoryValue\w*)\)\s*\{(.*?)\}', (headers/'HKCategoryValues.h').read_text(), re.S):
    values = {}
    for line in body.splitlines():
        m = re.match(r'\s*'+name+r'(\w+).*?=\s*(\d+)\s*,?', line)
        if m: values[int(m[2])] = labels(m[1])
    enums[name] = values
rows = []
for line in (headers/'HKTypeIdentifiers.h').read_text().splitlines():
    m = re.match(r'HK_EXTERN HK(Quantity|Category)TypeIdentifier const HK\1TypeIdentifier(\w+) API_AVAILABLE\(.*?watchos\((\d+)\.(\d+)\).*?;\s*//\s*(.*)', line)
    if not m: continue
    kind, name, major, minor, comment = m.groups()
    values = enums.get(comment.strip(), {}) if kind == 'Category' else {}
    value_literal = '[' + ', '.join(f'{k}: {json.dumps(v)}' for k,v in values.items()) + ']' if values else '[:]'
    if kind == 'Category' and not values:
        raise ValueError(f'Missing category value labels: {name}: {comment}')
    rows.append(f'        .init(kind: .{kind.lower()}, suffix: "{name}", title: "{labels(name)}", minimumOS: ({major}, {minor}), categoryValues: {value_literal}),')
text = '''// Generated by scripts/generate-health-catalog.py from Xcode 26.3's public watchOS SDK.
import Foundation
import HealthKit

struct HealthMetric {
    enum Kind { case quantity, category }
    let kind: Kind
    let suffix: String
    let title: String
    let minimumOS: (Int, Int)
    let categoryValues: [Int: String]
    var type: HKSampleType? {
        guard ProcessInfo.processInfo.isOperatingSystemAtLeast(OperatingSystemVersion(majorVersion: minimumOS.0, minorVersion: minimumOS.1, patchVersion: 0)) else { return nil }
        switch kind {
        case .quantity: return HKQuantityType.quantityType(forIdentifier: HKQuantityTypeIdentifier(rawValue: "HKQuantityTypeIdentifier" + suffix))
        case .category: return HKCategoryType.categoryType(forIdentifier: HKCategoryTypeIdentifier(rawValue: "HKCategoryTypeIdentifier" + suffix))
        }
    }
    static let catalog: [HealthMetric] = [
''' + '\n'.join(rows) + '\n    ]\n}\n'
Path('Watch/HealthCatalog.swift').write_text(text)
print(f'Generated {len(rows)} quantity/category identifiers')
